### ISSUE TITLE
How do I get started?

### ISSUE THREAD

**Issue by leostera** [alexfeh/ChromeAddon#1]
:smile:

**Comment by leostera** [comment]
D:

**Comment by alexfeh** [comment]
:O

**Comment by leostera** [comment]
Being serious, how do I get this running locally?

**Comment by alexfeh** [comment]
it is never running locally
the content of the folder gets uploaded to "chrome://extensions/" in the chrome browser by clicking the button "Load unpacked extension" and that's it.
After changing the code it will get updated by clicking the reload button there.

**Comment by leostera** [comment]
@alexfeh perfect, so I just clone this and go to `chrome://extensions` to try to load it with `Load unpacked extension`?

**Comment by alexfeh** [comment]
jep :)

**Comment by leostera** [comment]
Cool! That worked. It crashed my Chrome on a blog with about 600 links xD
